le_bateria  : le_bateria.c
	gcc -o le_bateria le_bateria.c -lwiringPi -lpthread
le_rede  : le_rede.c
	gcc -o le_rede le_rede.c -lwiringPi -lpthread
le_corr_bat  : le_corr_bat.c
	gcc -o le_corr_bat le_corr_bat.c -lwiringPi -lpthread

